### ISSUE TITLE
Build needs newer version of glm than is specified in CMakeLists.txt

### ISSUE THREAD

**Issue by kcozens** [cbernardo/kicad_oce_3D#4]
The CMakeLists file (as of commit 98e72c1c, Mar 15 16:01:08 2016 +1100) checks for version 0.9.5.1 or later of GLM. I have this version installed on my system but when I tried to build kicad_oce_3D the compiler complained that glm/gtx/matrix_decompose.hpp could not be found.

Using git to look at the history of GLM, the header was not added until after 0.9.5.4 and 0.9.6.0 is the next release listed and the first release that would have the file. The version number on line 273 of CmakeLists.txt needs to be updated to 0.9.6.0.

**Comment by cbernardo** [comment]
Thanks; I'll bump the version.
